name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # only run pull request when multiple trigger workflow
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Cache Ruby Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle Install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Danger linting
      uses: MeilCli/danger-action@v5
      with:
        plugins_file: Gemfile
        install_path: vendor/bundle
        danger_file: Dangerfile
        danger_id: danger-pr
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

  tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # only run pull request when multiple trigger workflow
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Cache Ruby Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle Install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run Tests
      run: |
        bundle config path vendor/bundle
        bundle exec rake test
